name: Test running setup-licensed

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

  # run on demand
  workflow_dispatch:

jobs:
  gem:
    runs-on: ubuntu-latest

    steps:
      # checkout the repo
      - uses: meta-introspector/checkout@v3
      
      # install ruby
      - uses: meta-introspector/setup-ruby@v1
        with:
          bundler-cache: 'true'
          ruby-version: "3.0"

      # install node
      - uses: meta-introspector/setup-node@v3
        with:
          node-version: "18.x"

      # run the action
      - name: Run setup-licensed
        uses: ./
        with:
          version: '4.x'

  exe:
    runs-on: ubuntu-latest

    steps:
      # checkout the repo
      - uses: meta-introspector/checkout@v3
      
      # do not install ruby

      # install node
      - uses: meta-introspector/setup-node@v3
        with:
          node-version: "18.x"

      # run the action
      - name: Run setup-licensed
        uses: ./
        with:
          version: '3.x'
